source "https://rubygems.org"

gem "google-protobuf", "~> 3.25"
gem "grpc", "~> 1.60"
gem "toml-rb", "~> 2.2"
gem "pycall", "~> 1.5"

group :development, :test do
  gem "grpc-tools", "~> 1.60"
  gem "minitest", "~> 5.20"
  gem "rake", "~> 13.0"
  gem "webmock", "~> 3.20"
  gem "simplecov", "~> 0.22.0"
  gem "standard", ">= 1.35.1"
  gem "solargraph", "~> 0.56.1", require: false
end
